title:             Quem faz acontecer
email:             your-email@example.com
description:       "Quando uma mulher dá um passo, todas estamos mais próximas da vitória."
author:            Start Bootstrap
baseurl:           "/"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
